services:
  nanoshare:
    image: xw134/nanoshare:latest
    ports:
      - "8080:8080"
    volumes:
      - data:./app/data
    restart: unless-stopped

networks:
  nanoshare_net:
    driver: bridge

volumes:
  data:
